### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by teohaik** [mqlight/nodejs-mqlight#9] opened 2017-06-01 13:44 UTC
Hello,

Iam facing the following error on npm install procedure:

The system cannot find the path specified.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mqlight"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! mqlight@2.0.2017053000 postinstall: `cd ./node_modules/amqp10 && npm install --production . && cd -`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mqlight@2.0.2017053000 postinstall script 'cd ./node_modules/amqp10 && npm install --production . && cd -'.
npm ERR! This is most likely a problem with the mqlight package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./node_modules/amqp10 && npm install --production . && cd -
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mqlight
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls mqlight
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\projects\my-app\npm-debug.log

**Comment by dnwe** [comment] 2017-06-01 16:05
Hi @teohaik – a dupe of #8 I think. Seems like there is a problem with the latest node package, possibly Windows-only, but I'm waiting to confirm that

**Comment by teohaik** [comment] 2017-06-01 20:15
hello @dnwe ,

yeap! You are correct, sorry for that! Nevertheless, we are waiting for an official update!

**Comment by dnwe** [comment] 2017-06-09 10:32
Closing as dupe of #8 which should hopefully be fixed by `mqlight@2.0.2017060901`

**Closed as completed by dnwe** 2017-06-09 10:32 UTC
